services:
  db:
    image: postgres:17-bullseye
    container_name: live-sport-dash-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - live-sport-dash-network


volumes:
  pgdata:

networks:
  live-sport-dash-network:
    driver: bridge  