version: "3.8"

services:
  db:
    image: postgres:17-bullseye
    container_name: live-sport-dash-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: live_sport_dash
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - live-sport-dash-network


volumes:
  pgdata:

networks:
  live-sport-dash-network:
    driver: bridge  